appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: iJVwctoWkD216Klkoqjq3cuQ+grXuPIn172UkjFO/tsYKXWOP01EE0VM5QFs+ivArkgELdRrYNrx7uo4U/X4a9zqFjV8in7qexYNs9KyeqJvu0KU+Wj9/WtDEauNHk92I6alFaqCNXQgog2h2bL/8cV6EEz8NT/B2WT0ydYuYd20yBxXJV9PPM8bhM1DIMABeqUfP96PPbm6b/l65xp3YpxohlKUex/ZrQB2h2DhX12Y/92kmgVa8TziqHmtiYIDGawK4zzn9v7bjWWElYO30rKu8CUsPQGqALH3UsPre44rfOLfoEpdSoYkU/JAoKNERAhosCk1QGaaBx/fb0BNCdY8Yy4N2aHX0SwTR7Ahd3A+OXox1JPXzYheGfdUQLfpmrupPv9fsVO8Ccpt9/Hbso4KrfmNhe++qg1XZ5K3Pfhj8TBbkqD2vrabxpwYjwCNXeIk/vMURkWfQaZFmB1kH6AmaE2FxhYRaTCqeUes57vcCpIAKWaBUzRWWlarPUdrxjyjPy5ubFDF6pZktRbuFKZjTDNjOIo4/AGVEf1J0Z7HBZi51qMFtSKiYWD7xnAT4RNUFYXrG3nOzpCet3mYvDzGmXoTYVwplJ8AhgQiaAkxBvvNHxJJDXEblko676UqLf9onSXD0trwBUuPG7Ybyb3+FZ4XRaOcINGpZ74IEJ4=
conda_forge_output_validation: true
